/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CognitiveRouteImport } from './routes/cognitive'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ParkinsonRouteImport } from './routes/parkinson'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as StrokeRouteImport } from './routes/stroke'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveRoute = CognitiveRouteImport.update({
  id: '/cognitive',
  path: '/cognitive',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkinsonRoute = ParkinsonRouteImport.update({
  id: '/parkinson',
  path: '/parkinson',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const StrokeRoute = StrokeRouteImport.update({
  id: '/stroke',
  path: '/stroke',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/history': typeof HistoryRoute
  '/parkinson': typeof ParkinsonRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/stroke': typeof StrokeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/history': typeof HistoryRoute
  '/parkinson': typeof ParkinsonRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/stroke': typeof StrokeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/history': typeof HistoryRoute
  '/parkinson': typeof ParkinsonRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/stroke': typeof StrokeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cognitive'
    | '/history'
    | '/parkinson'
    | '/profile'
    | '/progress'
    | '/recommendations'
    | '/stroke'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cognitive'
    | '/history'
    | '/parkinson'
    | '/profile'
    | '/progress'
    | '/recommendations'
    | '/stroke'
  id:
    | '__root__'
    | '/'
    | '/cognitive'
    | '/history'
    | '/parkinson'
    | '/profile'
    | '/progress'
    | '/recommendations'
    | '/stroke'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CognitiveRoute: typeof CognitiveRoute
  HistoryRoute: typeof HistoryRoute
  ParkinsonRoute: typeof ParkinsonRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RecommendationsRoute: typeof RecommendationsRoute
  StrokeRoute: typeof StrokeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive': {
      id: '/cognitive'
      path: '/cognitive'
      fullPath: '/cognitive'
      preLoaderRoute: typeof CognitiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkinson': {
      id: '/parkinson'
      path: '/parkinson'
      fullPath: '/parkinson'
      preLoaderRoute: typeof ParkinsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroke': {
      id: '/stroke'
      path: '/stroke'
      fullPath: '/stroke'
      preLoaderRoute: typeof StrokeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CognitiveRoute: CognitiveRoute,
  HistoryRoute: HistoryRoute,
  ParkinsonRoute: ParkinsonRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RecommendationsRoute: RecommendationsRoute,
  StrokeRoute: StrokeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
