/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CognitiveRouteImport } from './routes/cognitive'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ParkinsonRouteImport } from './routes/parkinson'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as StrokeRouteImport } from './routes/stroke'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CognitiveRoute = CognitiveRouteImport.update({
  id: '/cognitive',
  path: '/cognitive',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkinsonRoute = ParkinsonRouteImport.update({
  id: '/parkinson',
  path: '/parkinson',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const StrokeRoute = StrokeRouteImport.update({
  id: '/stroke',
  path: '/stroke',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/parkinson': typeof ParkinsonRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/stroke': typeof StrokeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/parkinson': typeof ParkinsonRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/stroke': typeof StrokeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cognitive': typeof CognitiveRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/mcp': typeof McpRoute
  '/parkinson': typeof ParkinsonRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/recommendations': typeof RecommendationsRoute
  '/stroke': typeof StrokeRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cognitive'
    | '/emergency'
    | '/history'
    | '/mcp'
    | '/parkinson'
    | '/profile'
    | '/progress'
    | '/recommendations'
    | '/stroke'
    | '/.well-known/oauth-protected-resource'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cognitive'
    | '/emergency'
    | '/history'
    | '/mcp'
    | '/parkinson'
    | '/profile'
    | '/progress'
    | '/recommendations'
    | '/stroke'
    | '/.well-known/oauth-protected-resource'
  id:
    | '__root__'
    | '/'
    | '/cognitive'
    | '/emergency'
    | '/history'
    | '/mcp'
    | '/parkinson'
    | '/profile'
    | '/progress'
    | '/recommendations'
    | '/stroke'
    | '/.well-known/oauth-protected-resource'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CognitiveRoute: typeof CognitiveRoute
  EmergencyRoute: typeof EmergencyRoute
  HistoryRoute: typeof HistoryRoute
  McpRoute: typeof McpRoute
  ParkinsonRoute: typeof ParkinsonRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  RecommendationsRoute: typeof RecommendationsRoute
  StrokeRoute: typeof StrokeRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cognitive': {
      id: '/cognitive'
      path: '/cognitive'
      fullPath: '/cognitive'
      preLoaderRoute: typeof CognitiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parkinson': {
      id: '/parkinson'
      path: '/parkinson'
      fullPath: '/parkinson'
      preLoaderRoute: typeof ParkinsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stroke': {
      id: '/stroke'
      path: '/stroke'
      fullPath: '/stroke'
      preLoaderRoute: typeof StrokeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CognitiveRoute: CognitiveRoute,
  EmergencyRoute: EmergencyRoute,
  HistoryRoute: HistoryRoute,
  McpRoute: McpRoute,
  ParkinsonRoute: ParkinsonRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  RecommendationsRoute: RecommendationsRoute,
  StrokeRoute: StrokeRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
